Fixed bug in table count check, and added in encryption test check
Percona-QA/pxc-qa pull request #13
Opened 2022-10-31 17:04 UTC by saikumar-vs

2022-11-01 11:22 UTC, saikumar-vs commented
Fix(s):

1) Fix bug with table row count logic

2) enable table row count for encryption test.

Testing Summary:
https://pxc.cd.percona.com/view/QA 8.0/job/pxc80_qa_framework_run/

#83 is old run branch(before fix)
min-bionic-x64
tests
correctness/crash_recovery.py
suite/ssl/ssl_qa.py

#84 run with fix
min-bionic-x64
tests
correctness/crash_recovery.py
suite/ssl/ssl_qa.py

#85 run with new fix and test encryption check added
min-bionic-x64
new test
suite/ssl/encryption.py

How to verify ( run tests with -d)
Before fix only one table in schema for cluster was checked,
After fix you should find more tables row count being checked.
Look for text in Jenkins o/p: "Table count test."

2022-11-01 16:13 UTC, eleo007 requested changes

2022-11-01 16:13 UTC, eleo007 commented on suite/ssl/encryption_qa.py
> +        if int(version) < int("080000"):
As discussed in a call:
- checksum.sanity_check does not perform any checks of DBs consistency but checks whether pt-checksum is installed and creates user and DB. Need to check whether we need checksum at all for tests. 
- not sure whether we need to move this block after sysbench as this is preparation step.

2022-11-01 16:13 UTC, eleo007 commented on suite/ssl/encryption_qa.py
> +        else:
Based on above: "if" part is not related to checks of tables consistency so we should not add consistency check in else block. + this will add consistency check only for 8.0 but not 5.7. Better place for consistency checks seems to be in 'encryption_qa' function if there is no check now.

2022-11-01 16:13 UTC, eleo007 commented on util/utility.py
> +        if result == 0 or result is None:
The "None" result as a successful result code seems to be a bit unexpected. We use it here to pass the "continue" in https://github.com/Percona-QA/pxc-qa/pull/13/files#diff-67b18f147213369955c00b435674927a17a57eb8e897cc69a9fa20b19a613ebfL90 . Maybe there is another way than continue? (try/finally or smth else? )

2022-11-02 05:06 UTC, saikumar-vs commented on suite/ssl/encryption_qa.py
> +        if int(version) < int("080000"):
Hi Elenora, 
Thanks for the quick review.
1. yes this seems like a know problem, i didnt attempt to fix this for 5.7. Like we discussed i'll try to work on it separately and report its findings
2. i will revert this change, as its only for 5.7 -- and handle it separately hopefully as part of 1 above.

2022-11-02 05:07 UTC, saikumar-vs commented on suite/ssl/encryption_qa.py
> +        else:
Ok, will move the check in encryption_qa function. ( addressed in latest patch).

2022-11-02 05:24 UTC, saikumar-vs commented on util/utility.py
> +        if result == 0 or result is None:
Ok, as we discussed will keep the result code as original, moved the logic within the table_count method to return 0. This is addressed in the latest patch.

2022-11-02 09:11 UTC, eleo007 approved these changes

2022-11-03 06:06 UTC, saikumar-vs commented
Fixed bug in table count check, and added in encryption test check (merge)

2022-11-03 06:11 UTC, merged